### ISSUE TITLE
Make token compatible with gitlab CI variable masking

### ISSUE THREAD

**Issue by keiranmraine** [VertebrateResequencing/wr#210]
It would be nice if the tokens generated for WR could be masked in GitLab CI:

https://docs.gitlab.com/ce/ci/variables/#masked-variables

Alternatively, the ability to specify the token when starting the manager.

**Comment by sb10** [comment]
Sorry, I don't understand the context or meaning of this request (not a GitLab CI user). Can you explain a bit more please?

You can "cheat" and place a file called `client.token` in the managerdir, and that token will be used by the manager.

**Comment by keiranmraine** [comment]
Having the generated token consist of characters from the Base64 alphabet, see `Table 1: The Base 64 Alphabet` of [rfc4648 section 4](https://tools.ietf.org/html/rfc4648#section-4).

Just to confirm by understanding of the `client.token` file.  If I create `.wr_production/client.token` before running `wr manager start` it will use that token?

**Comment by sb10** [comment]
Yes, if the token file already exists, `wr manager start` will use it.

I'm not getting why maskability is desired. Where and how is the token appearing in which logs, and why is that a problem? Are you running `wr manager start` as part of some end-to-end tests? Does it matter if a one-time-use token leaks out, when the manager no longer exists because the tests finished?

**Comment by sb10** [comment]
In any case, I'm not opposed to getting rid of the `_-` symbols since they're annoying in certain copy paste scenarios.

But the tokens are already base64 encoded: https://github.com/VertebrateResequencing/wr/blob/913578592064273e107ca0c8dc5bb02ea2886fa2/jobqueue/utils.go#L63-L67

Patch welcome to get it do to what you want.

**Comment by keiranmraine** [comment]
We're setting up GitLab CI to trigger large scale tests (algorithm integration on real data) using WR.  The manager host is going to be pre-configured and the gitlab ci will use the PyWrClient code to submit jobs to it.  This way we only take large OpenStack instances when we need to, rather than have them sitting idle for long periods of time.

GitLab ci will execute something along the lines:

```
python3 wrCi.py -u $CASMCI_WR_URL -t $CASMCI_WR_TOKEN ... 
```

If the WR token doesn't have `-_` then gitlab can mask the value in the logs.

Ideally we don't want it visible as the logs are available to anyone within our division using GitLab.  I'd hope people wouldn't abuse it but it's a possibility.  Only administrators can see group level CI/CD parameters.

**Comment by sb10** [comment]
I see, thanks for the background. So can your `wrCi.py` script work without the `-t` option, and you just use https://docs.gitlab.com/ce/ci/variables/#variable-types "File" option?

I can't make the token "normal" base64 because then it wouldn't work in URLs. I suppose `-_` could be replaced with eg. `a` or something, but that seems like a bad idea.

**Comment by keiranmraine** [comment]
I'd love to use the file option, unfortunately out gitlab instance isn't of high enough version (despite asking before the last round of maint).

I'm happy to work around until we get files, just thought I'd see if it was something that could be easily handled for future users.

**Comment by sb10** [comment]
Ok, I'll close this then since there isn't a safe&secure solution on wr's end. Something to be fixed by a gitlab upgrade on your end.
