### ISSUE TITLE
cloud_ram vs memory + docker

### ISSUE THREAD

**Issue by keiranmraine** [VertebrateResequencing/wr#215]
I've just had a WR job running docker fail after ~8h with an out of memory error.

It appears that although cloud_memory was set to ~48GB and the docker container was using up to ~30GB at points that WR was only concerned with the monitoring processes memory usage.

This was submitted via REST API with default `memory` (not specified, WR UI indicated 1G) and `--cloud_ram 48000`.

Docker container is monitored by specifying a uuid as the container name, and I have many jobs indicating the appropriate details being collected via this route:

<img width="1076" alt="Screen Shot 2019-07-08 at 21 25 53" src="https://user-images.githubusercontent.com/3740323/60840290-0f5fa100-a1c7-11e9-987a-79c7ca067912.png">

**Comment by sb10** [comment]
Why use cloud_ram and not memory?

Setting cloud_ram means wr will only spawn worker instances that on flavours with at least that much ram (for the Operating System). But since wr thinks your jobs only need 1GB RAM, it will schedule 2 of them per machine (because 48GB or ram requires a *.large flavour instance, and they all have 8 cores, and your jobs use 4 cores each).

I guess the machine ran out of memory because there were 2 of your jobs running at once and one of them used all the memory? Or, do you have details of the error and what killed the job?

Does the reported peak ram on successful jobs seem accurate? I'm not sure what you mean by "only concerned with the monitoring processes memory usage".

Try not setting cloud_ram, and setting memory to something realistic instead. Use --cloud_flavor to limit to certain flavours if that's something you're trying to achieve.

**Comment by keiranmraine** [comment]
The image example was from a different run with different params, and I know only 1 job was on the host.

How far over the "Expected RAM", "Expected Time" "Expected Disk" would WR allow before it kills a  job/host?

I wondered if the job was killed because the stdout/stderr exceeded 1G of the parent process.

Anyway I'll make the suggested changes and report back, I'd quite clearly mis-used the `--cloud_memory` param.

**Comment by sb10** [comment]
Jobs are never killed for going over time. Stdout/err of any size is supported, since wr only captures the head and tail of it.

Jobs are only killed (by wr) for using too much ram if the peak memory captured by wr is greater than the requested ram _and_ it's greater than 90% of machine memory.

Jobs are not currently killed for using too much disk, though perhaps the same rule as per ram should be used.

The goal of killing jobs is only to protect the whole machine from crashing, not to punish jobs for having inaccurate requested resources.

**Comment by keiranmraine** [comment]
Switching to `--memory` instead os `--cloud_memory` has resolved this issue, thanks.
