### ISSUE TITLE
LSF scheduler: allow custom resource reservation

### ISSUE THREAD

**Issue by mcshane** [VertebrateResequencing/wr#229]
e.g. add `-R "avx"` so we can select only nodes supporting AVX.

**Comment by sb10** [comment]
This has been implemented in https://github.com/VertebrateResequencing/wr/pull/230 . You will say:
`wr add --misc '-R "avx"'`

However, due to quoting issues it is not fully free-form. Please advise if there are any other options you would want to pass to LSF.

Feel free to review and accept the pull request yourself to get it merged in sooner.

**Comment by sb10** [comment]
PR accepted

**Comment by fgeorgatos** [comment]
while on $subject, if this is still relevant, there is a technique to generalise on this feature beyond merely `avx`, described over here (apologies, this requires to prove you are a human): 
* https://lists.ugent.be/wws/arc/easybuild/2019-11/msg00016.html
* https://lists.ugent.be/wws/arc/easybuild/2019-11/msg00017.html

If the nearby sysadmin wishes to discuss the solution, I'd be more than happy to do so. 
btw. That solution was actually prototyped for a well known system that is located at Hinxton.

**Comment by sb10** [comment]
FYI, the next release of wr will allow you to pass anything except single quotes: `--misc 'anything "at all"'`, which should cover all needs.
