### ISSUE TITLE
Runner should kill commands that go over reserved resources

### ISSUE THREAD

**Issue by sb10** [VertebrateResequencing/wr#23]
Since not all schedulers will kill the `wr runner` when the command it runs goes over memory/time reservations, runner itself should track this and issue the kill signal in a friendly LSF-type way, but only if actually threatening machine memory.

**Comment by keiranmraine** [comment]
Note that WR cannot track memory usage of a docker container due to it being outside of the process tree.

It is possible to have either name (`--name`) the container or have docker drop the container id to file (`--cidfile`) so I guess an job option to tell WR where to get the value from could be made available for jobs that have a docker component:

https://docs.docker.com/engine/reference/run/#container-identification

then:

```
docker stats --format "{{.MemUsage}}" <NAME/CID>
```

Obviously the `--cidfile` option would help determine if the docker component of the job has started as the file won't exist until it does while `--name` would potentially give errors if the docker portion of a job hasn't started.

**Comment by sb10** [comment]
Should make this a user option, if they want to run without limits.

**Comment by sb10** [comment]
Decided against making this optional. Changed killing to only when a cmd uses more memory than physical memory on the machine.
