### ISSUE TITLE
"timed out waiting for server to become ACTIVE" on Cromwell + WR + Openstack

### ISSUE THREAD

**Issue by tnguyensanger** [VertebrateResequencing/wr#249]
Any suggestions on how to debug or fix "server failed spawn" issues?

We are using Cromwell to run bioinformatic workflows on Openstack.  Since Cromwell doesn't have an Openstack backend, we use WR as the backend scheduler to execute cromwell jobs on openstack.

WR jobs often fail with these errors in the WR logs:
````
t=2020-03-04T16:44:51+0000 lvl=warn msg="server failed spawn" scheduler=openstack call=1b8eef2d6335f6a7 server=failed err="timed out waiting for server to become ACTIVE" caller=openstack.go:974
t=2020-03-04T17:10:07+0000 lvl=warn msg="server went bad, won't be used again" scheduler=openstack call=c87c46d7dfd4c85f server=59bd1e23-ccd1-4c1f-8b16-f2d82b5eb892 caller=openstack.go:1160
t=2020-03-04T17:10:07+0000 lvl=warn msg="failed to run command" scheduler=openstack call=c87c46d7dfd4c85f server=59bd1e23-ccd1-4c1f-8b16-f2d82b5eb892 cmd="(umask 7 && /usr/local/wr/wr runner -s '7400:780:1:0:f38ced7bea90d309f5258ec999660ed8' --deployment production --server '192.168.0.11:5021' --domain localhost -r 1 -m 781)" err="cloud RunCmd((umask 7 && /usr/local/wr/wr runner -s '7400:780:1:0:f38ced7bea90d309f5258ec999660ed8' --deployment production --server '192.168.0.11:5021' --domain localhost -r 1 -m 781)) failed: wait: remote command exited without exit status or exit signal" caller=openstack.go:1167

````

We've had issues where openstack was too busy and we would get different errors when that happened.  
````
t=2020-03-02T16:47:46+0000 lvl=warn msg="server failed spawn" scheduler=openstack call=ff231a8c1a1a4d5e server=failed err="No valid host was found. There are not enough hosts available." caller=openstack.go:974
t=2020-03-02T16:47:46+0000 lvl=warn msg="server failed to spawn due to lack of hardware" scheduler=openstack flavor=m2.xlarge caller=openstack.go:983
````

We suspect that openstack has sufficient resources when we experience "timed out waiting for server to become ACTIVE" errors.  In the past, we have deleted the $HOME/.wr_production directory, and restarted wr from scratch, and that seems to alleviate the problems for a few days/weeks.

**Comment by sb10** [comment]
`timed out waiting for server to become ACTIVE` occurs under these specific circumstances:

1. An API request to create a new server was successful
2. After checking the Status of the new server every second for 4*(current exponentially weighted moving average of past successful spawn times), it is still neither "ACTIVE" not "ERROR"

If restarting wr helps (there would be no benefit to deleting `$HOME/.wr_production`, it suggests a scenario where:

1. OpenStack was fast and responsive, and new servers were being created very quickly for some time
2. OpenStack becomes more than 4x slower than it was at bringing up new servers
3. It remains that slow until you give up waiting

This can be solved by waiting longer than 4x, or taking a user-defined server timeout value, but a timeout and error does need to be there, or you'd potentially be left in a situation where OpenStack is unable to properly create new servers (despite there being enough apparent resources), but wr silently keeps waiting forever and doesn't tell you about the problem.

`server failed to spawn due to lack of hardware`, as the error suggests, means that there is not enough physical hardware available to create a new server.

In both cases, wr is correctly identifying a real problem in OpenStack that you should log and track and feed back to your OpenStack environment administrators, so they can investigate and improve the situation for you.

**Comment by tnguyensanger** [comment]
> This can be solved by waiting longer than 4x, or taking a user-defined server timeout value, 

Are these properties that we can configure via the $HOME/.wr_config.yml or otherwise?

**Comment by sb10** [comment]
> > This can be solved by waiting longer than 4x, or taking a user-defined server timeout value,
> Are these properties that we can configure via the $HOME/.wr_config.yml or otherwise?

No, I'd have to make changes to wr. But as I alluded to, there's no point increasing the timeout if all it results in is you getting the error after a longer period of time. I'd first try investigating some of the affected servers and find out why they didn't become "ACTIVE" after >=90s. It's possible they would never have become active, because there was a problem with the hypervisor.

**Comment by tnguyensanger** [comment]
Good tip.  We'll have to increase our ````cloudautoconfirmdead```` property.  By the time we discover the errors, the servers have long since deleted.  Is there any way to figure out what the timeout for waiting for a server to become ACTIVE is (without WR code changes)?

**Comment by sb10** [comment]
One change I'll certainly make is improve the debugging to report the server ID and timeout duration for those errors.

With your existing logs, you can try grepping the "call" (1b8eef2d6335f6a7 in the example above), and comparing the timestamp of the previous event, which likely would have been shortly before creating the server.

**Comment by sb10** [comment]
Improved logs are now in wr 0.21. Grep for "timing out on it ever becoming ACTIVE" to find the new messages. The minimum timeout was also increased from 90 to 180s.
