### ISSUE TITLE
Retry backoff feature

### ISSUE THREAD

**Issue by kjsanger** [VertebrateResequencing/wr#416]
When one of our jobs fails because of an intermittent problem and is retried, we beileve that the retry attempt(s) can be quite eager, exhausting the available retries before whatever service glitched out has recovered.

I looked at the code and didn't see backoff implemented for job retries. If that's correct, something like a truncated exponential backoff would be a nice feature to have.

**Comment by sb10** [comment]
Hi, backoff is implemented as entering the delay queue, from which jobs automatically move to the ready queue after a fixed 30 seconds.

I can quite easily implement a truncated exponential backoff for this instead; what sort of min, max and step do you feel would be appropriate? How many retries do you currently make use of?

**Comment by mgcam** [comment]
We only do one retry - a blank setting for all jobs. We could move to setting this per job. There is one job, which fails because of a database lock, which could benefit from a few retries, say in 5 mins, 15 mins, 40 mins. It's difficult to me to suggest something in general.

**Comment by sb10** [comment]
If it's a specific job that needs specific retry behaviour, I'd suggest the best solution (that works across multiple workflow management systems) is to integrate the retry in to the job itself, since only it will know when it is encountering the database lock issue, or some other issue, and only it will know if a retry is appropriate.

If that's not possible, then a generic backoff in wr for all jobs should work fine. I can cap it at 1hr, and have it scale up from 30s. It would fire more than just at 5,15,40mins, but I don't think that would be an issue for you? For your problematic job you'd just set the retries to some very high value.

With a min 30s, max 3600s, and a increase factor of 1.5x per step, it would retry after:
30,45,68,101,152,228,342,513,769,1153,1730,2595,3600 seconds. Cumulative 189mins.
With a factor of 2x, it would retry after:
30,60,120,240,480,960,1920,3600 seconds. Cumulative 124mins.
(the times would be jittered to avoid stampeding hoard effect)

What are your thoughts? For wr's default of 3 retries, both of these options seem fine and beneficial for all use cases.

**Comment by mgcam** [comment]
> If it's a specific job that needs specific retry behaviour, I'd 
> suggest the best solution (that works across multiple workflow 
> management systems) is to integrate the retry in to the job itself, 
> since only it will know when it is encountering the database lock 
> issue, or some other issue, and only it will know if a retry is 
> appropriate.
>
I'd rather go with a more generic solution, which is a retry offered by 
the job manager.
>
> If that's not possible, then a generic backoff in wr for all jobs 
> should work fine. I can cap it at 1hr, and have it scale up from 30s. 
> It would fire more than just at 5,15,40mins, but I don't think that 
> would be an issue for you?
>
Not a problem to retry many times (I think) for this particular one and 
many others
>
> For your problematic job you'd just set the retries to some very high 
> value.
>
> With a min 30s, max 3600s, and a increase factor of 1.5x per step, it 
> would retry after:
> 30,45,68,101,152,228,342,513,769,1153,1730,2595,3600 seconds. 
> Cumulative 189mins.
> With a factor of 2x, it would retry after:
> 30,60,120,240,480,960,1920,3600 seconds. Cumulative 124mins.
> (the times would be jittered to avoid stampeding hoard effect)
>
> What are your thoughts? For wr's default of 3 retries, both of these 
> options seem fine and beneficial for all use cases.
>
I'd say factor of 2 will space out the jobs better. Setting the max 
possible value to 8 attempts in your second schedule should be enough.

We have some jobs that fail after many hours of compute. In most cases 
they need a fix, so trying them again cannot give us anything. However, 
occasionally they fail early (problems with mounting lustre, iRODS 
problems) and can be retried, preferably after a pause. What do you 
think is appropriate in this case?

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [github.com] 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_VertebrateResequencing_wr_issues_416-23issuecomment-2D902524865&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=N0cZBaVFsqc9cWqoLjIDsg&m=cYWKY9chLSBvpjUaGh8Qn3Hqx0OS0QjGxPz8_x6P03o&s=TpQi8A8M27CEYsBQP2iezETD-MoFCBprc-BkzwVVlaI&e=>, 
> or unsubscribe [github.com] 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAQGQRC25LI5W47WM4O4EETT5YGI5ANCNFSM5COLVOVA&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=N0cZBaVFsqc9cWqoLjIDsg&m=cYWKY9chLSBvpjUaGh8Qn3Hqx0OS0QjGxPz8_x6P03o&s=0LBjI7KtTWfgYIlVQPUlq2OzcUPuq3_ZDPL5MmU2ZhY&e=>.
> Triage notifications on the go with GitHub Mobile for iOS 
> [apps.apple.com] 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=N0cZBaVFsqc9cWqoLjIDsg&m=cYWKY9chLSBvpjUaGh8Qn3Hqx0OS0QjGxPz8_x6P03o&s=pYxZedDIQFVpF-3Qia96P1dA0rM_EKVk-ZOs4GD4bok&e=> 
> or Android [play.google.com] 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26utm-5Fcampaign-3Dnotification-2Demail&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=N0cZBaVFsqc9cWqoLjIDsg&m=cYWKY9chLSBvpjUaGh8Qn3Hqx0OS0QjGxPz8_x6P03o&s=mV-QEnP5bvHvduTH_VKOKARdNkwyVTjM944U_ULWAtk&e=>.
>



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by sb10** [comment]
I'll implement the backoff with a factor of 2 then.

I think "if it fails early, retry, otherwise do not" might be a common enough situation to add a `--no_retry_over_walltime 5m` option. In this example, if the job takes longer than 5mins and fails, there will be no retry. If it fails in less than 5mins, the normal retry behaviour with the new backoff would occur.

Would that work for you? Adding this option does mean storing another small bit of data on every single job, so your database will get slightly larger.

**Comment by mgcam** [comment]
On 20/08/2021 10:26, Sendu Bala wrote:
>
> I'll implement the backoff with a factor of 2 then.
>
> I think "if it fails early, retry, otherwise do not" might be a common 
> enough situation to add a |--no_retry_over_walltime 5m| option. In 
> this example, if the job takes longer than 5mins and fails, there will 
> be no retry. If it fails in less than 5mins, the normal retry 
> behaviour with the new backoff would occur.
>
I think this would be good, will ask others to look at this thread.
>
> Would that work for you? Adding this option does mean storing another 
> small bit of data on every single job, so your database will get 
> slightly larger.
>
That's OK...
>
>



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by kjsanger** [comment]
I think this will be generally useful and the handling of jobs that fail slowly is a good idea.

**Comment by sb10** [comment]
These features will be in the next release, due at the end of the month.
