### ISSUE TITLE
wr mod: option to change the LSF queue

### ISSUE THREAD

**Issue by mcshane** [VertebrateResequencing/wr#427]
Can change the time, but sometime just want to change the queue without remembering how long each queue will max out with.

Could also perhaps `bswitch` queue for running jobs (if possible).

**Comment by sb10** [comment]
Thanks again for the feature request. This has been implemented and will be available in this month's release.

No `bswitch` was implemented, because you can only `wr mod` jobs that aren't running, so this wouldn't be relevant. Also, bswitch is not always reliable, can be confusing, and may be disabled on a given LSF farm.
