### ISSUE TITLE
Cloud deployments: manager resilience

### ISSUE THREAD

**Issue by keiranmraine** [VertebrateResequencing/wr#83]
At present if the master node is lost I don't believe it is possible to recover the system without teardown?

Would it be possible to create a 'set' of masters via a 'wr attach' where by you provide the host where an existing 'wr deploy' or other 'wr attach' instance has been started.

Each attached instance would report itself as a slave unless the 'master' is no longer contactable.  At this point the instance with the earliest start time would become the 'master'.

Jobs passed to any instance would route requests to the current 'master'.

Would require additional teardown options to indicate if just the current master/slave or whole deployment is destroyed.

e.g.
```
hostA $ wr deploy....
hostB $ wr attach hostA
hostC $ wr attach hostA
hostD $ wr attach hostB
```

At this point `wr add` on hosts A-D are routed to hostA.

```
hostA $ wr teardown manager=hostA
```
hostA performs clean shutdown.  hostB becomes manager.

```
hostB $ kill $wr_manager_pid
```
Simulate death of wr manager on hostB, hostC becomes manager.

Thoughts?

**Comment by sb10** [comment]
Manager resilience in the cloud is certainly a planned feature. The ultimate form would be that when you deploy you specify how much redundancy you want, and it then spawns that many 'head' nodes, and then uses some form of coordination between the managers running on each so that if one goes down, another takes over (and brings up another redundant server).

But before this extreme (and "wastage" of head nodes that just sit there idly doing nothing), however, the idea is that on a single head node wr manager will back up it's database to S3. If the head node goes down, you'd teardown --force (any running jobs would fail anyway) and then deploy as normal. The difference being, the new manager would pick up the previously stored database and so be able to restart (from scratch) any jobs that were previously running, and have any jobs pending that were previously pending.

**Comment by sb10** [comment]
The simpler stop gap is that you just redeploy which picks up past state (already implemented). The new thing to implement is that currently running jobs are able to connect to the manager and things don't get rerun.

**Comment by sb10** [comment]
If the head node is lost, you now just redeploy, it picks up past state, and currently running jobs reconnect to the new manager.

This does assume you use your own certs and token, and backup the db to s3.

It is a manual process where you have to know the head node went down in order to redeploy it, but I don't think "high availability" is an important feature for wr, at least for now. I prefer not wasting resources on spare head nodes.

I'm closing this for now, but if you think HA _is_ important, please create a new issue.
